######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 16 15:39:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

CONFIG += staticlib

# Input
HEADERS += fluidmodel.h mainwindow.h
SOURCES += fluidmodel.cpp main.cpp mainwindow.cpp
